  name: "deploy on aws"

  on: workflow_dispatch
  jobs:
    deploy:
        runs-on: self-hosted
        steps:
            - name: "setup node js"
              uses: actions/setup-node@v4
              with:
                node-version: 'v22.12.0'

            - name: "checkout code"
              uses: actions/checkout@v3

            - name: "install dependencies"
              run: npm install

            - name: "run the test"
              run: npm run test

              
            - name: "deploy on aws"
              run: pm2 start src/index.js



        




